2021-05-25 08:33:33.427 [error] <0.1054.0> CRASH REPORT Process <0.1054.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621920813,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621920813},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...},...}
2021-05-25 08:33:33.433 [error] <0.1054.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.1053.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621920813,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621920813},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...}
2021-05-25 08:39:03.297 [error] <0.725.0> CRASH REPORT Process <0.725.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921143,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621921143},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...},...}
2021-05-25 08:39:03.303 [error] <0.725.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921143,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621921143},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...}
2021-05-25 08:46:42.377 [error] <0.725.0> CRASH REPORT Process <0.725.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921602,disease => <<"wer">>,drug => <<"DVF">>,updated_at => 1621921602},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => #{self => <<...>>}}],...},...]},...},...},...}
2021-05-25 08:46:42.384 [error] <0.725.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921602,disease => <<"wer">>,drug => <<"DVF">>,updated_at => 1621921602},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => #{self => <<"...">>}}],...},...]},...},...}
2021-05-25 08:47:20.740 [error] <0.726.0> CRASH REPORT Process <0.726.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921640,disease => <<"wer_updated">>,drug => <<"DVF_updated">>,updated_at => 1621921640},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => ...}],...},...]},...},...},...}
2021-05-25 08:47:20.740 [error] <0.726.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921640,disease => <<"wer_updated">>,drug => <<"DVF_updated">>,updated_at => 1621921640},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => ...}],...},...]},...},...}
2021-05-25 08:48:15.751 [error] <0.728.0> CRASH REPORT Process <0.728.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921695,description => <<"response to good joke">>,name => <<"laughter">>,updated_at => 1621921695},id => <<"23">>,links => #{self => <<"http://localhost/symptom/23">>},relationships => #{},type => <<"symptom">>},included => [],...}],...},...]},...},...},...}
2021-05-25 08:48:15.751 [error] <0.728.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921695,description => <<"response to good joke">>,name => <<"laughter">>,updated_at => 1621921695},id => <<"23">>,links => #{self => <<"http://localhost/symptom/23">>},relationships => #{},type => <<"symptom">>},included => [],links => ...}],...},...]},...},...}
2021-05-25 08:48:33.611 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-25 08:48:33.611 [error] <0.729.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
