2021-05-25 08:33:33.427 [error] <0.1054.0> CRASH REPORT Process <0.1054.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621920813,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621920813},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...},...}
2021-05-25 08:33:33.433 [error] <0.1054.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.1053.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621920813,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621920813},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...}
2021-05-25 08:39:03.297 [error] <0.725.0> CRASH REPORT Process <0.725.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921143,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621921143},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...},...}
2021-05-25 08:39:03.303 [error] <0.725.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921143,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621921143},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...}
2021-05-25 08:46:42.377 [error] <0.725.0> CRASH REPORT Process <0.725.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921602,disease => <<"wer">>,drug => <<"DVF">>,updated_at => 1621921602},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => #{self => <<...>>}}],...},...]},...},...},...}
2021-05-25 08:46:42.384 [error] <0.725.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921602,disease => <<"wer">>,drug => <<"DVF">>,updated_at => 1621921602},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => #{self => <<"...">>}}],...},...]},...},...}
2021-05-25 08:47:20.740 [error] <0.726.0> CRASH REPORT Process <0.726.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921640,disease => <<"wer_updated">>,drug => <<"DVF_updated">>,updated_at => 1621921640},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => ...}],...},...]},...},...},...}
2021-05-25 08:47:20.740 [error] <0.726.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921640,disease => <<"wer_updated">>,drug => <<"DVF_updated">>,updated_at => 1621921640},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => ...}],...},...]},...},...}
2021-05-25 08:48:15.751 [error] <0.728.0> CRASH REPORT Process <0.728.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921695,description => <<"response to good joke">>,name => <<"laughter">>,updated_at => 1621921695},id => <<"23">>,links => #{self => <<"http://localhost/symptom/23">>},relationships => #{},type => <<"symptom">>},included => [],...}],...},...]},...},...},...}
2021-05-25 08:48:15.751 [error] <0.728.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921695,description => <<"response to good joke">>,name => <<"laughter">>,updated_at => 1621921695},id => <<"23">>,links => #{self => <<"http://localhost/symptom/23">>},relationships => #{},type => <<"symptom">>},included => [],links => ...}],...},...]},...},...}
2021-05-25 08:48:33.611 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-25 08:48:33.611 [error] <0.729.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 08:21:53.273 [error] <0.529.0> CRASH REPORT Process <0.529.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 08:21:53.282 [error] <0.529.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.528.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 08:22:10.428 [error] <0.530.0> CRASH REPORT Process <0.530.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 08:22:10.428 [error] <0.530.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.528.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 08:34:18.854 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 08:34:18.863 [error] <0.524.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.523.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 08:40:12.763 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 08:40:12.770 [error] <0.524.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.523.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 08:42:45.313 [error] <0.527.0> CRASH REPORT Process <0.527.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:42:45.314 [error] <0.527.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.526.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:42:55.003 [error] <0.528.0> CRASH REPORT Process <0.528.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:42:55.003 [error] <0.528.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.526.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:45.802 [error] <0.531.0> CRASH REPORT Process <0.531.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:45.802 [error] <0.531.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:54.388 [error] <0.532.0> CRASH REPORT Process <0.532.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:54.388 [error] <0.532.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:55.565 [error] <0.533.0> CRASH REPORT Process <0.533.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:55.565 [error] <0.533.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:56.054 [error] <0.534.0> CRASH REPORT Process <0.534.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:56.054 [error] <0.534.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:56.471 [error] <0.535.0> CRASH REPORT Process <0.535.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:56.471 [error] <0.535.0> Cowboy stream 5 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:56.736 [error] <0.536.0> CRASH REPORT Process <0.536.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:56.736 [error] <0.536.0> Cowboy stream 6 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:57.063 [error] <0.537.0> CRASH REPORT Process <0.537.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:57.063 [error] <0.537.0> Cowboy stream 7 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:57.346 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:57.346 [error] <0.538.0> Cowboy stream 8 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:57.628 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:57.628 [error] <0.539.0> Cowboy stream 9 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:57.901 [error] <0.540.0> CRASH REPORT Process <0.540.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:57.902 [error] <0.540.0> Cowboy stream 10 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:58.159 [error] <0.541.0> CRASH REPORT Process <0.541.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:58.160 [error] <0.541.0> Cowboy stream 11 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:58.517 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:58.517 [error] <0.542.0> Cowboy stream 12 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:58.810 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:58.810 [error] <0.543.0> Cowboy stream 13 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:46:20.514 [error] <0.546.0> CRASH REPORT Process <0.546.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:46:20.514 [error] <0.546.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:46:21.419 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:46:21.420 [error] <0.547.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:47:02.632 [error] <0.548.0> CRASH REPORT Process <0.548.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => #{attributes => #{created_at => 1622094422,rating => 3,text => <<"he did a great job reparing my knee!">>,updated_at => 1622094422},id => <<"6">>,links => #{self => <<"http://localhost/feedback/6">>},relationships => #{},type => <<"feedback">>},included => [],...}],...},...]},...},...},...}
2021-05-27 08:47:02.632 [error] <0.548.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => #{attributes => #{created_at => 1622094422,rating => 3,text => <<"he did a great job reparing my knee!">>,updated_at => 1622094422},id => <<"6">>,links => #{self => <<"http://localhost/feedback/6">>},relationships => #{},type => <<"feedback">>},included => [],links => ...}],...},...]},...},...}
2021-05-27 08:47:14.860 [error] <0.549.0> CRASH REPORT Process <0.549.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:47:14.861 [error] <0.549.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:48:22.991 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 08:48:22.999 [error] <0.524.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.523.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 11:14:11.912 [error] <0.731.0> CRASH REPORT Process <0.731.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:14:11.919 [error] <0.731.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.730.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:16:45.705 [error] <0.735.0> CRASH REPORT Process <0.735.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:16:45.705 [error] <0.735.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.734.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:17:10.376 [error] <0.736.0> CRASH REPORT Process <0.736.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:17:10.376 [error] <0.736.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.734.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:17:45.357 [error] <0.737.0> CRASH REPORT Process <0.737.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:17:45.358 [error] <0.737.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.734.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:19:43.552 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => [{<<"Content-type">>,<<"application/json">>}]},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,...},...]},...]},...},...},...}
2021-05-27 11:19:43.558 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => [{<<"Content-type">>,<<"application/json">>}]},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"l..."},...]},...]},...},...}
2021-05-27 11:24:34.725 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:24:34.731 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:25:02.343 [error] <0.544.0> CRASH REPORT Process <0.544.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:25:02.343 [error] <0.544.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:27:29.820 [error] <0.548.0> CRASH REPORT Process <0.548.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:27:29.820 [error] <0.548.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.547.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:27:43.461 [error] <0.549.0> CRASH REPORT Process <0.549.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => [#{attributes => #{created_at => 1621401032,disease => <<"fever">>,drug => <<"aspirin">>,updated_at => 1621401032},id => <<"2">>,links => #{self => <<"http://localhost/treatment/2">>},relationships => #{},type => <<"treatment">>},#{attributes => #{created_at => ...,...},...},...],...}],...},...]},...},...},...}
2021-05-27 11:27:43.461 [error] <0.549.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.547.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => [#{attributes => #{created_at => 1621401032,disease => <<"fever">>,drug => <<"aspirin">>,updated_at => 1621401032},id => <<"2">>,links => #{self => <<"http://localhost/treatment/2">>},relationships => #{},type => <<"treatment">>},#{attributes => #{created_at => ...,...},...},...],...}],...},...]},...},...}
2021-05-27 11:32:47.456 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:32:47.458 [error] <0.553.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.552.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:39:28.473 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:39:28.479 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:40:45.338 [error] <0.546.0> CRASH REPORT Process <0.546.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:40:45.339 [error] <0.546.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:40:52.865 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:40:52.865 [error] <0.547.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:50:43.779 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:50:43.785 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:03:15.667 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 12:03:15.672 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:11:47.273 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,34}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 12:11:47.280 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,34}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:17:45.474 [error] <0.548.0> CRASH REPORT Process <0.548.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 12:17:45.474 [error] <0.548.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.547.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 12:20:19.898 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 12:20:19.905 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:20:29.672 [error] <0.545.0> CRASH REPORT Process <0.545.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 12:20:29.672 [error] <0.545.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.544.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 12:25:44.957 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 12:25:44.957 [error] <0.553.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.552.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:26:08.130 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 12:26:08.131 [error] <0.555.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.554.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 12:26:20.243 [error] <0.558.0> CRASH REPORT Process <0.558.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 12:26:20.243 [error] <0.558.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.554.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:26:22.967 [error] <0.559.0> CRASH REPORT Process <0.559.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 12:26:22.968 [error] <0.559.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.554.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 07:48:53.149 [error] <0.530.0> CRASH REPORT Process <0.530.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-28 07:48:53.156 [error] <0.530.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.529.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 07:49:05.203 [error] <0.532.0> CRASH REPORT Process <0.532.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => [<<>>]},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-28 07:49:05.203 [error] <0.532.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.529.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => [<<>>]},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-28 07:49:16.226 [error] <0.533.0> CRASH REPORT Process <0.533.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-28 07:49:16.227 [error] <0.533.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.529.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 07:59:49.673 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Parsers.UnsupportedMediaTypeError',media_type => <<"application/octet-stream">>,plug_status => 415},[{'Elixir.Plug.Parsers',reduce,8,[{file,"lib/plug/parsers.ex"},{line,357}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Downloads/facultate_stef/master_anul..."},...]},...]},...},...},...}
2021-05-28 07:59:49.680 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Parsers.UnsupportedMediaTypeError',media_type => <<"application/octet-stream">>,plug_status => 415},[{'Elixir.Plug.Parsers',reduce,8,[{file,"lib/plug/parsers.ex"},{line,357}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Downloads/facultate_stef/master_anul1_..."},...]},...]},...},...}
2021-05-28 08:02:49.837 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-28 08:02:49.845 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 08:03:10.456 [error] <0.546.0> CRASH REPORT Process <0.546.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1622178190,description => <<"tre">>,name => <<"abc">>,updated_at => 1622178190},id => <<"10">>,links => #{self => <<"http://localhost/symptom/10">>},relationships => #{},type => <<"symptom">>},included => [],links => #{self => <<"...">>}}],...},...]},...},...},...}
2021-05-28 08:03:10.456 [error] <0.546.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1622178190,description => <<"tre">>,name => <<"abc">>,updated_at => 1622178190},id => <<"10">>,links => #{self => <<"http://localhost/symptom/10">>},relationships => #{},type => <<"symptom">>},included => [],links => #{self => <<"ht...">>}}],...},...]},...},...}
2021-05-28 08:03:21.581 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-28 08:03:21.581 [error] <0.547.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 08:28:10.957 [error] <0.750.0> CRASH REPORT Process <0.750.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => #{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...},...}],...},...]},...},...},...}
2021-05-28 08:28:10.963 [error] <0.750.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.749.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => #{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => <<..>>},...}],...},...]},...},...}
2021-05-28 08:28:28.344 [error] <0.751.0> CRASH REPORT Process <0.751.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...}],...}],...},...]},...},...},...}
2021-05-28 08:28:28.344 [error] <0.751.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.749.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...}],...}],...},...]},...},...}
2021-05-28 08:29:03.405 [error] <0.754.0> CRASH REPORT Process <0.754.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => #{attributes => #{created_at => 1622179743,date => <<"12-04-2021">>,doctor => <<"Dr Jeffrey Kabouli">>,patient => <<"Alex Porinton">>,updated_at => 1622179743},id => <<"10">>,links => #{self => <<"http://localhost/appointment/10">>},relationships => #{},...},...}],...},...]},...},...},...}
2021-05-28 08:29:03.405 [error] <0.754.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.749.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => #{attributes => #{created_at => 1622179743,date => <<"12-04-2021">>,doctor => <<"Dr Jeffrey Kabouli">>,patient => <<"Alex Porinton">>,updated_at => 1622179743},id => <<"10">>,links => #{self => <<"http://localhost/appointment/10">>},relationships => #{},type => ...},...}],...},...]},...},...}
2021-05-28 08:29:13.480 [error] <0.756.0> CRASH REPORT Process <0.756.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-28 08:29:13.481 [error] <0.756.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.749.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-28 08:29:25.263 [error] <0.758.0> CRASH REPORT Process <0.758.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-28 08:29:25.264 [error] <0.758.0> Cowboy stream 5 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.749.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 08:30:56.408 [error] <0.761.0> CRASH REPORT Process <0.761.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.HospitalView'},[{'Elixir.Api.Views.HospitalView',id,[#{data => [#{attributes => #{available_beds => 12,city => <<"Bucharest">>,created_at => 1621833653,name => <<"Spital 1">>,specialization => <<"Oncologic">>,updated_at => 1621833653},id => <<"11">>,links => #{self => <<"http://localhost/hospital/11">>},relationships => #{},...},...],...}],...},...]},...},...},...}
2021-05-28 08:30:56.408 [error] <0.761.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.760.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.HospitalView'},[{'Elixir.Api.Views.HospitalView',id,[#{data => [#{attributes => #{available_beds => 12,city => <<"Bucharest">>,created_at => 1621833653,name => <<"Spital 1">>,specialization => <<"Oncologic">>,updated_at => 1621833653},id => <<"11">>,links => #{self => <<"http://localhost/hospital/11">>},relationships => #{},...},...],...}],...},...]},...},...}
2021-05-28 08:31:06.217 [error] <0.764.0> CRASH REPORT Process <0.764.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => [#{attributes => #{created_at => 1621401032,disease => <<"fever">>,drug => <<"aspirin">>,updated_at => 1621401032},id => <<"2">>,links => #{self => <<"http://localhost/treatment/2">>},relationships => #{},type => <<"treatment">>},#{attributes => #{created_at => ...,...},...},...],...}],...},...]},...},...},...}
2021-05-28 08:31:06.217 [error] <0.764.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.760.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => [#{attributes => #{created_at => 1621401032,disease => <<"fever">>,drug => <<"aspirin">>,updated_at => 1621401032},id => <<"2">>,links => #{self => <<"http://localhost/treatment/2">>},relationships => #{},type => <<"treatment">>},#{attributes => #{created_at => ...,...},...},...],...}],...},...]},...},...}
2021-05-28 08:31:22.169 [error] <0.766.0> CRASH REPORT Process <0.766.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-28 08:31:22.170 [error] <0.766.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.760.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-31 08:54:51.963 [error] <0.523.0> CRASH REPORT Process <0.523.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [],included => [],links => #{self => <<"http://localhost/symptom">>}}],[{file,"lib/views/symptom_view.ex"},{line,2}]},{'Elixir.JSONAPI.Serializer',encode_data,4,[{file,"lib/jsonapi/serializer.ex"},{line,44}]},{'Elixir.JSONAPI.Serializer',serialize,3,[{file,"lib/j..."},...]},...]},...},...},...}
2021-05-31 08:54:51.967 [error] <0.523.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.522.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [],included => [],links => #{self => <<"http://localhost/symptom">>}}],[{file,"lib/views/symptom_view.ex"},{line,2}]},{'Elixir.JSONAPI.Serializer',encode_data,4,[{file,"lib/jsonapi/serializer.ex"},{line,44}]},{'Elixir.JSONAPI.Serializer',serialize,3,[{file,"lib/jso..."},...]},...]},...},...}
2021-05-31 08:55:26.791 [error] <0.527.0> CRASH REPORT Process <0.527.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1622440526,description => <<"could be a symptom for a lot of things">>,name => <<"coughing">>,updated_at => 1622440526},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"symptom">>},...}],...},...]},...},...},...}
2021-05-31 08:55:26.792 [error] <0.527.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.522.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1622440526,description => <<"could be a symptom for a lot of things">>,name => <<"coughing">>,updated_at => 1622440526},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"symptom">>},included => ...,...}],...},...]},...},...}
2021-05-31 08:55:44.005 [error] <0.528.0> CRASH REPORT Process <0.528.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1622440526,description => <<"could be a symptom for a lot of things">>,name => <<"coughing">>,updated_at => 1622440526},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"symptom">>}],...}],...},...]},...},...},...}
2021-05-31 08:55:44.006 [error] <0.528.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.522.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1622440526,description => <<"could be a symptom for a lot of things">>,name => <<"coughing">>,updated_at => 1622440526},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"symptom">>}],...}],...},...]},...},...}
