2021-05-24 18:43:43.055 [error] <0.687.0> CRASH REPORT Process <0.687.0> with 2 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.BadMapError',term => nil},[{'Elixir.Map',get,[nil,<<"user_login">>,nil],[{file,"lib/map.ex"},{line,469}]},{'Elixir.Api.Router','-do_match/4-fun-6-',2,[{file,"lib/api_test/router.ex"},{line,161}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},...]},...},...},...}
2021-05-24 18:43:43.058 [error] <0.687.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.684.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.BadMapError',term => nil},[{'Elixir.Map',get,[nil,<<"user_login">>,nil],[{file,"lib/map.ex"},{line,469}]},{'Elixir.Api.Router','-do_match/4-fun-6-',2,[{file,"lib/api_test/router.ex"},{line,161}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},...]},...},...}
2021-05-24 18:44:52.211 [error] <0.691.0> CRASH REPORT Process <0.691.0> with 2 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.BadMapError',term => nil},[{'Elixir.Map',get,[nil,<<"user_login">>,nil],[{file,"lib/map.ex"},{line,469}]},{'Elixir.Api.Router','-do_match/4-fun-6-',2,[{file,"lib/api_test/router.ex"},{line,161}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},...]},...},...},...}
2021-05-24 18:44:52.211 [error] <0.691.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.690.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.BadMapError',term => nil},[{'Elixir.Map',get,[nil,<<"user_login">>,nil],[{file,"lib/map.ex"},{line,469}]},{'Elixir.Api.Router','-do_match/4-fun-6-',2,[{file,"lib/api_test/router.ex"},{line,161}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},...]},...},...}
2021-05-24 18:54:21.249 [error] <0.541.0> CRASH REPORT Process <0.541.0> with 2 neighbours exited with reason: {{{{noproc,{gen_server,call,[<0.530.0>,{call,{'basic.publish',0,<<"my_api">>,<<"api.login.auth-login.events">>,false,false},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,<<"auth_service">>,undefined},<<"{\"name\":\"utilizator1\"}">>},<0.541.0>},70000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 65,...}},...},...]}},...},...}
2021-05-24 18:54:21.253 [error] <0.541.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.540.0> had its request process exit with reason: {{{noproc,{gen_server,call,[<0.530.0>,{call,{'basic.publish',0,<<"my_api">>,<<"api.login.auth-login.events">>,false,false},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,<<"auth_service">>,undefined},<<"{\"name\":\"utilizator1\"}">>},<0.541.0>},70000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 65,cert => ...,...}},...},...]}},...}
2021-05-27 08:21:53.141 [error] <0.550.0> CRASH REPORT Process <0.550.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-27 08:21:53.145 [error] <0.550.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.546.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-27 08:22:10.424 [error] <0.552.0> CRASH REPORT Process <0.552.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-27 08:22:10.425 [error] <0.552.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.546.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-27 08:33:33.773 [error] <0.525.0> CRASH REPORT Process <0.525.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-27 08:33:33.777 [error] <0.525.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.521.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-27 08:34:18.753 [error] <0.527.0> CRASH REPORT Process <0.527.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-27 08:34:18.753 [error] <0.527.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.521.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-27 08:38:39.199 [error] <0.525.0> CRASH REPORT Process <0.525.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-27 08:38:39.203 [error] <0.525.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.521.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-27 12:17:45.457 [error] <0.529.0> CRASH REPORT Process <0.529.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-27 12:17:45.461 [error] <0.529.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.528.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-27 12:20:29.658 [error] <0.527.0> CRASH REPORT Process <0.527.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-27 12:20:29.661 [error] <0.527.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.526.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-27 12:26:08.125 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-27 12:26:08.125 [error] <0.539.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.538.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-27 12:26:22.965 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-27 12:26:22.965 [error] <0.542.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.538.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-28 07:48:53.127 [error] <0.532.0> CRASH REPORT Process <0.532.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-28 07:48:53.130 [error] <0.532.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.531.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-28 07:49:16.225 [error] <0.534.0> CRASH REPORT Process <0.534.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-28 07:49:16.225 [error] <0.534.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.531.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-28 08:02:49.813 [error] <0.526.0> CRASH REPORT Process <0.526.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-28 08:02:49.816 [error] <0.526.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.525.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-28 08:03:21.579 [error] <0.528.0> CRASH REPORT Process <0.528.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-28 08:03:21.579 [error] <0.528.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.525.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-28 08:28:28.350 [error] <0.527.0> CRASH REPORT Process <0.527.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-28 08:28:28.353 [error] <0.527.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.526.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-28 08:29:13.479 [error] <0.530.0> CRASH REPORT Process <0.530.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-28 08:29:13.479 [error] <0.530.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.526.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-28 08:29:25.261 [error] <0.532.0> CRASH REPORT Process <0.532.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-28 08:29:25.261 [error] <0.532.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.526.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-28 08:30:56.402 [error] <0.541.0> CRASH REPORT Process <0.541.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-28 08:30:56.402 [error] <0.541.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.540.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-28 08:31:06.215 [error] <0.544.0> CRASH REPORT Process <0.544.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-28 08:31:06.215 [error] <0.544.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.540.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-28 08:31:22.167 [error] <0.546.0> CRASH REPORT Process <0.546.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/D..."},...]},...]},...},...},...}
2021-05-28 08:31:22.168 [error] <0.546.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.540.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Dow..."},...]},...]},...},...}
2021-05-31 08:45:50.512 [error] <0.702.0> CRASH REPORT Process <0.702.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTig..."},...]},...]},...},...},...}
2021-05-31 08:45:50.516 [error] <0.702.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.701.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTiger..."},...]},...]},...},...}
2021-05-31 08:54:51.933 [error] <0.525.0> CRASH REPORT Process <0.525.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTig..."},...]},...]},...},...},...}
2021-05-31 08:54:51.936 [error] <0.525.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.524.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTiger..."},...]},...]},...},...}
2021-05-31 08:55:44.003 [error] <0.528.0> CRASH REPORT Process <0.528.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTig..."},...]},...]},...},...},...}
2021-05-31 08:55:44.003 [error] <0.528.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.524.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTiger..."},...]},...]},...},...}
2021-05-31 09:01:03.186 [error] <0.552.0> CRASH REPORT Process <0.552.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTig..."},...]},...]},...},...},...}
2021-05-31 09:01:03.187 [error] <0.552.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.551.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTiger..."},...]},...]},...},...}
2021-05-31 09:10:43.502 [error] <0.544.0> CRASH REPORT Process <0.544.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTig..."},...]},...]},...},...},...}
2021-05-31 09:10:43.506 [error] <0.544.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.543.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTiger..."},...]},...]},...},...}
2021-05-31 09:13:52.052 [error] <0.552.0> CRASH REPORT Process <0.552.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTig..."},...]},...]},...},...},...}
2021-05-31 09:13:52.052 [error] <0.552.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.551.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTiger..."},...]},...]},...},...}
2021-05-31 09:14:31.877 [error] <0.557.0> CRASH REPORT Process <0.557.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTig..."},...]},...]},...},...},...}
2021-05-31 09:14:31.877 [error] <0.557.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.551.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTiger..."},...]},...]},...},...}
2021-05-31 09:29:18.252 [error] <0.525.0> CRASH REPORT Process <0.525.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTig..."},...]},...]},...},...},...}
2021-05-31 09:29:18.256 [error] <0.525.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.524.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/IrishTiger..."},...]},...]},...},...}
