2021-05-24 18:43:43.055 [error] <0.687.0> CRASH REPORT Process <0.687.0> with 2 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.BadMapError',term => nil},[{'Elixir.Map',get,[nil,<<"user_login">>,nil],[{file,"lib/map.ex"},{line,469}]},{'Elixir.Api.Router','-do_match/4-fun-6-',2,[{file,"lib/api_test/router.ex"},{line,161}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},...]},...},...},...}
2021-05-24 18:43:43.058 [error] <0.687.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.684.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.BadMapError',term => nil},[{'Elixir.Map',get,[nil,<<"user_login">>,nil],[{file,"lib/map.ex"},{line,469}]},{'Elixir.Api.Router','-do_match/4-fun-6-',2,[{file,"lib/api_test/router.ex"},{line,161}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},...]},...},...}
2021-05-24 18:44:52.211 [error] <0.691.0> CRASH REPORT Process <0.691.0> with 2 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.BadMapError',term => nil},[{'Elixir.Map',get,[nil,<<"user_login">>,nil],[{file,"lib/map.ex"},{line,469}]},{'Elixir.Api.Router','-do_match/4-fun-6-',2,[{file,"lib/api_test/router.ex"},{line,161}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},...]},...},...},...}
2021-05-24 18:44:52.211 [error] <0.691.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.690.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.BadMapError',term => nil},[{'Elixir.Map',get,[nil,<<"user_login">>,nil],[{file,"lib/map.ex"},{line,469}]},{'Elixir.Api.Router','-do_match/4-fun-6-',2,[{file,"lib/api_test/router.ex"},{line,161}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},...]},...},...}
2021-05-24 18:54:21.249 [error] <0.541.0> CRASH REPORT Process <0.541.0> with 2 neighbours exited with reason: {{{{noproc,{gen_server,call,[<0.530.0>,{call,{'basic.publish',0,<<"my_api">>,<<"api.login.auth-login.events">>,false,false},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,<<"auth_service">>,undefined},<<"{\"name\":\"utilizator1\"}">>},<0.541.0>},70000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 65,...}},...},...]}},...},...}
2021-05-24 18:54:21.253 [error] <0.541.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.540.0> had its request process exit with reason: {{{noproc,{gen_server,call,[<0.530.0>,{call,{'basic.publish',0,<<"my_api">>,<<"api.login.auth-login.events">>,false,false},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,<<"auth_service">>,undefined},<<"{\"name\":\"utilizator1\"}">>},<0.541.0>},70000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 65,cert => ...,...}},...},...]}},...}
